name: Build and deploy JAR app to Azure Web App - comlab2-user-service

on:
  push:
    branches:
      - release/dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Specify the Java distribution
          java-version: '17'

      - name: Build with Maven
        run: mvn -f user-service/pom.xml clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: user-service-MS
          path: '${{ github.workspace }}/user-service/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: user-service-MS
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F0A3373D56414ABFABD80CA56C63DAAF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6737BBAA0B3344FA95032DD9317C3D4F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_02A70BF826FE4E31B2C20B0A171E22CF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'comlab2-user-service'
          slot-name: 'Production'
          package: '*.jar'
